// This file is auto-generated by @hey-api/openapi-ts

export type Account = {
    address: string;
    chain: SubscriptionChain;
    signature?: string;
};

export type AccountListResponse = {
    accounts: Array<TokenAccount>;
    reveal_message: string;
};

export type CreateAccount = {
    account: SubscriptionAccount;
    signature: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Subscription = {
    id: string;
    type: SubscriptionType;
    provider: SubscriptionProvider;
    started_at: number;
    ended_at?: number;
    is_active: boolean;
    provider_data: {
        [key: string]: unknown;
    };
    account: SubscriptionAccount;
    tags: Array<(string)>;
};

export type SubscriptionAccount = {
    address: string;
    chain: SubscriptionChain;
};

/**
 * An enumeration.
 */
export type SubscriptionChain = 'base' | 'solana';

/**
 * An enumeration.
 */
export type SubscriptionProvider = 'hold' | 'subs' | 'vouchers';

/**
 * An enumeration.
 */
export type SubscriptionType = 'pro' | 'advanced' | 'agent';

export type TokenAccount = {
    name: string;
    token?: string;
    sha1_token: string;
    owner: string;
    subscription: Subscription;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CheckAuthAuthCheckGetResponse = (unknown);

export type CheckAuthAuthCheckGetError = unknown;

export type TokenMessageTokenMessageGetResponse = (unknown);

export type TokenMessageTokenMessageGetError = unknown;

export type TokenCreateTokenPostData = {
    body: CreateAccount;
};

export type TokenCreateTokenPostResponse = (TokenAccount);

export type TokenCreateTokenPostError = (HTTPValidationError);

export type AccountStatusAccountAddressStatusGetData = {
    path: {
        address: unknown;
    };
};

export type AccountStatusAccountAddressStatusGetResponse = (unknown);

export type AccountStatusAccountAddressStatusGetError = (HTTPValidationError);

export type AccountDeleteAccountAddressDeleteResponse = (unknown);

export type AccountDeleteAccountAddressDeleteError = unknown;

export type AccountMetricsAccountMetricsSha1TokenGetData = {
    body: Account;
};

export type AccountMetricsAccountMetricsSha1TokenGetResponse = (unknown);

export type AccountMetricsAccountMetricsSha1TokenGetError = (HTTPValidationError);

export type AccountListAccountAddressListGetData = {
    path: {
        address: unknown;
    };
    query?: {
        chain?: string;
        reveal_message_signature?: string;
    };
};

export type AccountListAccountAddressListGetResponse = (AccountListResponse);

export type AccountListAccountAddressListGetError = (HTTPValidationError);