// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios';
import type { SubscribeHoldSubscriptionPostData, SubscribeHoldSubscriptionPostError, SubscribeHoldSubscriptionPostResponse, UnsubscribeHoldSubscriptionDeleteData, UnsubscribeHoldSubscriptionDeleteError, UnsubscribeHoldSubscriptionDeleteResponse, RefreshActiveHoldSubscriptionsHoldRefreshPostError, RefreshActiveHoldSubscriptionsHoldRefreshPostResponse, HoldSubscriptionMessagesHoldMessageGetData, HoldSubscriptionMessagesHoldMessageGetError, HoldSubscriptionMessagesHoldMessageGetResponse, RefreshSubsRefreshPostError, RefreshSubsRefreshPostResponse, GetUserSubscriptionsSubscriptionsGetData, GetUserSubscriptionsSubscriptionsGetError, GetUserSubscriptionsSubscriptionsGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Subscribe
 */
export const subscribeHoldSubscriptionPost = <ThrowOnError extends boolean = false>(options: Options<SubscribeHoldSubscriptionPostData, ThrowOnError>) => { return (options?.client ?? client).post<SubscribeHoldSubscriptionPostResponse, SubscribeHoldSubscriptionPostError, ThrowOnError>({
    ...options,
    url: '/hold/subscription'
}); };

/**
 * Unsubscribe
 */
export const unsubscribeHoldSubscriptionDelete = <ThrowOnError extends boolean = false>(options: Options<UnsubscribeHoldSubscriptionDeleteData, ThrowOnError>) => { return (options?.client ?? client).delete<UnsubscribeHoldSubscriptionDeleteResponse, UnsubscribeHoldSubscriptionDeleteError, ThrowOnError>({
    ...options,
    url: '/hold/subscription'
}); };

/**
 * Refresh Active Hold Subscriptions
 */
export const refreshActiveHoldSubscriptionsHoldRefreshPost = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).post<RefreshActiveHoldSubscriptionsHoldRefreshPostResponse, RefreshActiveHoldSubscriptionsHoldRefreshPostError, ThrowOnError>({
    ...options,
    url: '/hold/refresh'
}); };

/**
 * Hold Subscription Messages
 * Returns the messages to sign to authenticate other actions
 */
export const holdSubscriptionMessagesHoldMessageGet = <ThrowOnError extends boolean = false>(options: Options<HoldSubscriptionMessagesHoldMessageGetData, ThrowOnError>) => { return (options?.client ?? client).get<HoldSubscriptionMessagesHoldMessageGetResponse, HoldSubscriptionMessagesHoldMessageGetError, ThrowOnError>({
    ...options,
    url: '/hold/message'
}); };

/**
 * Refresh
 * Cancel existing unpaid subscriptions and creating newly paid ones
 */
export const refreshSubsRefreshPost = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).post<RefreshSubsRefreshPostResponse, RefreshSubsRefreshPostError, ThrowOnError>({
    ...options,
    url: '/subs/refresh'
}); };

/**
 * Get User Subscriptions
 */
export const getUserSubscriptionsSubscriptionsGet = <ThrowOnError extends boolean = false>(options: Options<GetUserSubscriptionsSubscriptionsGetData, ThrowOnError>) => { return (options?.client ?? client).get<GetUserSubscriptionsSubscriptionsGetResponse, GetUserSubscriptionsSubscriptionsGetError, ThrowOnError>({
    ...options,
    url: '/subscriptions'
}); };