// This file is auto-generated by @hey-api/openapi-ts

export type BaseSubscription = {
    id: string;
    type: SubscriptionType;
    provider: SubscriptionProvider;
    started_at: number;
    ended_at?: number;
    is_active: boolean;
};

export type GetUserSubscriptionsResponse = {
    subscriptions: Array<BaseSubscription>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type HoldDeleteSubscriptionBody = {
    account: SubscriptionAccount;
    signature: string;
    type: SubscriptionType;
    subscription_id: string;
};

export type HoldDeleteSubscriptionResponse = {
    success: boolean;
};

export type HoldGetMessagesResponse = {
    subscribe_message: string;
    unsubscribe_message: string;
};

export type HoldPostRefreshSubscriptionsResponse = {
    cancelled_subscriptions: Array<(string)>;
};

export type HoldPostSubscriptionBody = {
    account: SubscriptionAccount;
    signature: string;
    type: SubscriptionType;
};

export type HoldPostSubscriptionResponse = {
    post_hash: string;
    subscription_id: string;
};

export type SubsPostRefreshSubscriptionsResponse = {
    created_subscriptions: Array<(string)>;
    cancelled_subscriptions: Array<(string)>;
};

export type SubscriptionAccount = {
    address: string;
    chain: SubscriptionChain;
};

/**
 * An enumeration.
 */
export type SubscriptionChain = 'base';

/**
 * An enumeration.
 */
export type SubscriptionProvider = 'hold' | 'subs';

/**
 * An enumeration.
 */
export type SubscriptionType = 'standard';

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type SubscribeHoldSubscriptionPostData = {
    body: HoldPostSubscriptionBody;
};

export type SubscribeHoldSubscriptionPostResponse = (HoldPostSubscriptionResponse);

export type SubscribeHoldSubscriptionPostError = (HTTPValidationError);

export type UnsubscribeHoldSubscriptionDeleteData = {
    body: HoldDeleteSubscriptionBody;
};

export type UnsubscribeHoldSubscriptionDeleteResponse = (HoldDeleteSubscriptionResponse);

export type UnsubscribeHoldSubscriptionDeleteError = (HTTPValidationError);

export type RefreshActiveHoldSubscriptionsHoldRefreshPostResponse = (HoldPostRefreshSubscriptionsResponse);

export type RefreshActiveHoldSubscriptionsHoldRefreshPostError = unknown;

export type HoldSubscriptionMessagesHoldMessageGetData = {
    query: {
        subscription_type: SubscriptionType;
    };
};

export type HoldSubscriptionMessagesHoldMessageGetResponse = (HoldGetMessagesResponse);

export type HoldSubscriptionMessagesHoldMessageGetError = (HTTPValidationError);

export type RefreshSubsRefreshPostResponse = (SubsPostRefreshSubscriptionsResponse);

export type RefreshSubsRefreshPostError = unknown;

export type GetUserSubscriptionsSubscriptionsGetData = {
    query: {
        address: string;
    };
};

export type GetUserSubscriptionsSubscriptionsGetResponse = (GetUserSubscriptionsResponse);

export type GetUserSubscriptionsSubscriptionsGetError = (HTTPValidationError);