// This file is auto-generated by @hey-api/openapi-ts

export type BaseSubscription = {
    id: string;
    type: SubscriptionType;
    provider: SubscriptionProvider;
    started_at: number;
    ended_at?: number;
    is_active: boolean;
};

export type GetUserSubscriptionsResponse = {
    subscriptions: Array<BaseSubscription>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type HoldDeleteSubscriptionBody = {
    account: SubscriptionAccount;
    signature: string;
    type: SubscriptionType;
    subscription_id: string;
};

export type HoldDeleteSubscriptionResponse = {
    success: boolean;
};

export type HoldGetMessagesResponse = {
    subscribe_message: string;
    unsubscribe_message: string;
};

export type HoldPostRefreshSubscriptionsResponse = {
    cancelled_subscriptions: Array<(string)>;
};

export type HoldPostSubscriptionBody = {
    account: SubscriptionAccount;
    signature: string;
    type: SubscriptionType;
};

export type HoldPostSubscriptionResponse = {
    post_hash: string;
    subscription_id: string;
};

export type SubsPostRefreshSubscriptionsResponse = {
    created_subscriptions: Array<(string)>;
    cancelled_subscriptions: Array<(string)>;
};

export type Subscription = {
    id: string;
    type: SubscriptionType;
    provider: SubscriptionProvider;
    started_at: number;
    ended_at?: number;
    is_active: boolean;
    provider_data: {
        [key: string]: unknown;
    };
    account: SubscriptionAccount;
    tags: Array<(string)>;
};

export type SubscriptionAccount = {
    address: string;
    chain: SubscriptionChain;
};

/**
 * An enumeration.
 */
export type SubscriptionChain = 'base' | 'solana';

/**
 * An enumeration.
 */
export type SubscriptionProvider = 'hold' | 'subs' | 'vouchers';

/**
 * An enumeration.
 */
export type SubscriptionType = 'pro' | 'advanced' | 'agent';

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type VouchersCreatedSubscription = {
    account: SubscriptionAccount;
    type: SubscriptionType;
    end_time: number;
    post_hash: string;
    subscription_id: string;
};

export type VouchersDeleteSubscribeBody = {
    subscription_ids: Array<(string)>;
};

export type VouchersDeleteSubscriptionResponse = {
    cancelled_subscriptions: Array<(string)>;
    not_found_subscriptions: Array<(string)>;
};

export type VouchersPostRefreshSubscriptionsResponse = {
    cancelled_subscriptions: Array<(string)>;
};

export type VouchersPostSubscribeBody = {
    subscriptions: Array<VouchersSubscription>;
    password: string;
};

export type VouchersPostSubscriptionResponse = {
    created_subscriptions: Array<VouchersCreatedSubscription>;
};

export type VouchersSubscription = {
    account: SubscriptionAccount;
    type: SubscriptionType;
    end_time: number;
};

export type GetUserSubscriptionsSubscriptionsGetData = {
    query: {
        address: string;
        chain: SubscriptionChain;
    };
};

export type GetUserSubscriptionsSubscriptionsGetResponse = (GetUserSubscriptionsResponse);

export type GetUserSubscriptionsSubscriptionsGetError = (HTTPValidationError);

export type GetSubscriptionSubscriptionsSubscriptionIdGetData = {
    path: {
        subscription_id: string;
    };
};

export type GetSubscriptionSubscriptionsSubscriptionIdGetResponse = (Subscription);

export type GetSubscriptionSubscriptionsSubscriptionIdGetError = (HTTPValidationError);

export type SubscribeHoldSubscriptionPostData = {
    body: HoldPostSubscriptionBody;
};

export type SubscribeHoldSubscriptionPostResponse = (HoldPostSubscriptionResponse);

export type SubscribeHoldSubscriptionPostError = (HTTPValidationError);

export type UnsubscribeHoldSubscriptionDeleteData = {
    body: HoldDeleteSubscriptionBody;
};

export type UnsubscribeHoldSubscriptionDeleteResponse = (HoldDeleteSubscriptionResponse);

export type UnsubscribeHoldSubscriptionDeleteError = (HTTPValidationError);

export type RefreshActiveHoldSubscriptionsHoldRefreshPostResponse = (HoldPostRefreshSubscriptionsResponse);

export type RefreshActiveHoldSubscriptionsHoldRefreshPostError = unknown;

export type HoldSubscriptionMessagesHoldMessageGetData = {
    query: {
        subscription_type: SubscriptionType;
    };
};

export type HoldSubscriptionMessagesHoldMessageGetResponse = (HoldGetMessagesResponse);

export type HoldSubscriptionMessagesHoldMessageGetError = (HTTPValidationError);

export type RefreshSubsRefreshPostResponse = (SubsPostRefreshSubscriptionsResponse);

export type RefreshSubsRefreshPostError = unknown;

export type SubscribeVouchersSubscriptionPostData = {
    body: VouchersPostSubscribeBody;
};

export type SubscribeVouchersSubscriptionPostResponse = (VouchersPostSubscriptionResponse);

export type SubscribeVouchersSubscriptionPostError = (HTTPValidationError);

export type CancelVouchersSubscriptionsVouchersSubscriptionDeleteData = {
    body: VouchersDeleteSubscribeBody;
};

export type CancelVouchersSubscriptionsVouchersSubscriptionDeleteResponse = (VouchersDeleteSubscriptionResponse);

export type CancelVouchersSubscriptionsVouchersSubscriptionDeleteError = (HTTPValidationError);

export type RefreshActiveVouchersSubscriptionsVouchersRefreshPostResponse = (VouchersPostRefreshSubscriptionsResponse);

export type RefreshActiveVouchersSubscriptionsVouchersRefreshPostError = unknown;